version: "3"

services:
  simple-drag-drop-react-example:
    container_name: simple-drag-drop-react-example
    build:
      context: /
      dockerfile: Dockerfile
    image: simple-drag-drop-react-example
    restart: always
    network_mode: bridge
    env_file: .env
    ports:
      - "5501:5501"
